### ISSUE TITLE
Rename `overpass/*` to `overpass/*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [EqualStreetNames/equalstreetnames-berlin#8]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by jbelien** [comment]
Thanks a lot @FloEdelmann ! 👍 
I saw a similar PR in on other of the repository I manage. 😄 
Excellent idea IMHO, I'll make sure I apply this new "logic" to all the PR that I manage.

**Comment by FloEdelmann** [comment]
Nice, thank you! Please mention me in the PRs or commits if I didn't already open an issue in that repo yet, so that I can keep track of the repos using the new file extension :slightly_smiling_face:

**Comment by FloEdelmann** [comment]
Thanks for renaming and pinging me :blush:
